version: '3'
services:
  mariadb-master:
    image: mariadb:latest
    container_name: mariadb-master-server
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_DATABASE: master_test_db
      MARIADB_USER: db_user
      MARIADB_PASSWORD: testpassword
    ports:
      - '3308:3306'
    volumes:
      - mariadb-master-volume-data:/var/lib/mysql
      - ./etc/mariadb/etc.d/my.cnf:/etc/mysql/etc.d/cnf
    networks:
      - mariadb-server-network
volumes:
  mariadb-master-volume-data:

networks:
  mariadb-server-network:
    driver: bridge