version: '3'
services:
  mariadb-master:
    image: mariadb:latest
    container_name: mariadb-master-server
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - '3308:3306'
    volumes:
      - mariadb-master-volume-data:/var/lib/mysql
      - ./etc/mariadb/etc.d/my.cnf:/etc/mysql/etc.d/cnf
      - ./initdb:/docker-entrypoint-initdb.d
    networks:
      - mariadb-server-network
volumes:
  mariadb-master-volume-data:

networks:
  mariadb-server-network:
    driver: bridge